# Resolve server/requirements.in into a hash-pinned requirements.lock.
# Supply-chain rule: only releases uploaded >= 14 days ago are eligible.
param([int]$CooldownDays = 14)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$py = "$env:LOCALAPPDATA\hive\.venv\Scripts\python.exe"
$cutoff = (Get-Date).AddDays(-$CooldownDays).ToString('yyyy-MM-dd')
$dl = Join-Path $env:TEMP "hive-wheels"
if (Test-Path $dl) { Remove-Item -Recurse -Force $dl }
New-Item -ItemType Directory $dl | Out-Null

Write-Host "Resolving with uploads prior to $cutoff ..."
$ErrorActionPreference = 'Continue'   # pip writes notices to stderr; rely on exit code instead
& $py -m pip download --only-binary=:all: --uploaded-prior-to $cutoff -r "$root\server\requirements.in" -d $dl 2>&1 | Write-Host
$ErrorActionPreference = 'Stop'
if ($LASTEXITCODE -ne 0) { throw "pip download failed" }

$lines = @("# Generated by scripts/lock-python.ps1 on $(Get-Date -Format 'yyyy-MM-dd') (cooldown: $CooldownDays days, uploads before $cutoff)",
           "# Platform: win_amd64 / cp314. Install: pip install --require-hashes --no-deps -r requirements.lock")
Get-ChildItem $dl -Filter *.whl | Sort-Object Name | ForEach-Object {
    $parts = $_.Name.Split('-')
    $name = $parts[0].Replace('_', '-').ToLower()
    $ver = $parts[1]
    $hash = (Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLower()
    $lines += "$name==$ver \"
    $lines += "    --hash=sha256:$hash"
}
$lines | Set-Content -Encoding utf8 "$root\server\requirements.lock"
Write-Host "Wrote server/requirements.lock"
